<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aviator.Domain\Aviator.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="AutoMapper.Extensions" Version="2.1.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Blogs\Commands\CreateBlog\" />
    <Folder Include="Blogs\Commands\DeleteBlog\" />
    <Folder Include="Blogs\Commands\UpdateBlog\" />
    <Folder Include="Blogs\Queries\GetBlogById\" />
    <Folder Include="Blogs\Queries\GetBlogs\" />
    <Folder Include="Common\Behaviator\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Mappings\" />
  </ItemGroup>

</Project>
